name: ch-01-02-1

on: 
    pull_request:
        branches:
        - master

jobs:
    job1:
        name: First Job
        runs-on: ubuntu-latest
        steps:
            - name: Step one
              run: |
                  echo Step One
            - name: Step two
              run: |
                  echo Step Two
    job2:
        name: Second Job
        runs-on: windows-latest
        steps:
            - name: Step one
              run: |
                  echo Step one windows
            - name: Step two
              run: |
                  echo Step two windows
