name: using-other-actions

on: [pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Check out data repo
      uses: actions/checkout@v2
      with:
        repository: silverstone1903/covid19
        path: data
        ref: master
    - name: Check directory
      run: ls data
      
